
platform :ios, '10.0'
target 'Demo' do
use_frameworks!

# Pods for Demo

pod 'Alamofire', '~> 4.7', :inhibit_warnings => true
pod 'AlamofireLogger'
pod 'Starscream', '3.1.0'
pod 'OpenCV2', '~> 3.4.1'
pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '4.1.0'
pod 'lottie-ios'



end
